# ┌───────────────────────────────────────────┐
# │  PostgreSQL Configuration                 │
# │  Database: pulsepay_orders + outbox       │
# │  for development use ONLY                 │
# └───────────────────────────────────────────┘

listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 256MB
wal_level = replica
log_statement = 'all'
log_duration = on
